#pragma kernel CSMain

float Stepsize;
uint CanvasWidth;

RWStructuredBuffer<float4> Colors;
RWTexture2D<float4> OutputTexture;

[numthreads(8,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4 source = Colors[id.y * CanvasWidth + id.x];
    float r = source.x - Stepsize;
    float g = source.y - Stepsize;
    float b = source.z - Stepsize;
    float4 new_col = float4(r, g, b, 1);

    Colors[id.y * CanvasWidth + id.x] = new_col;
    OutputTexture[id.xy] = new_col;
}
