#pragma kernel CSMain

float Stepsize;

RWTexture2D<float4> InputTexture;
RWTexture2D<float4> OutputTexture;
RWTexture2D<float4> Result;

[numthreads(32,1,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    float4 source = InputTexture[id.xy];
    float r = source.x - Stepsize;
    float g = source.y - Stepsize;
    float b = source.z - Stepsize;
    float4 new_col = float4(r, g, b, 1);

    OutputTexture[id.xy] = new_col;
    Result[id.xy] = new_col;
}
